=== mohamethlo/Projet_XML_Technologie/applichat/src/main/resources/applichat.dtd
<!-- Racine -->
<!ELEMENT appliChat (cfg:environnements, utilisateurs, contacts, groupes, messages, notificationsRacine?, mod:plugins?, evt:busEvenements?, crdt:documents?, observabilite?, pipeline?, configurationSysteme)>
<!ATTLIST appliChat
    xmlns CDATA #FIXED "http://exemple.com/chat"
    xmlns:cfg CDATA #FIXED "http://exemple.com/chat/config"
    xmlns:mod CDATA #FIXED "http://exemple.com/chat/modules"
    xmlns:evt CDATA #FIXED "http://exemple.com/chat/evenements"
    xmlns:crdt CDATA #FIXED "http://exemple.com/chat/crdt"
    version CDATA #REQUIRED
    genereLe CDATA #REQUIRED>

<!-- Environnements -->
<!ELEMENT cfg:environnements (cfg:env+)>
<!ELEMENT cfg:env (cfg:endpointAPI, cfg:flagsFonctionnalites)>
<!ATTLIST cfg:env nom CDATA #REQUIRED>
<!ELEMENT cfg:endpointAPI (#PCDATA)>
<!ELEMENT cfg:flagsFonctionnalites (cfg:flag+)>
<!ELEMENT cfg:flag EMPTY>
<!ATTLIST cfg:flag nom CDATA #REQUIRED active (true|false) #REQUIRED>

<!-- Utilisateurs -->
<!ELEMENT utilisateurs (utilisateur+)>
<!ELEMENT utilisateur (identifiants, profil, preferences, journalActivite?)>
<!ATTLIST utilisateur id ID #REQUIRED cfg:env CDATA #IMPLIED>

<!-- Identifiants -->
<!ELEMENT identifiants (login, motDePasse, authentification2FA?)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT motDePasse (#PCDATA)>
<!ATTLIST motDePasse algoHash CDATA #REQUIRED>
<!ELEMENT authentification2FA EMPTY>
<!ATTLIST authentification2FA methode CDATA #REQUIRED active (true|false) #REQUIRED>

<!-- Profil -->
<!ELEMENT profil (nom, photo, bio?, languePreferee, languesDisponibles, fuseauHoraire, statut)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT bio (#PCDATA)>
<!ELEMENT languePreferee (#PCDATA)>
<!ELEMENT languesDisponibles (langue+)>
<!ELEMENT langue EMPTY>
<!ATTLIST langue code CDATA #REQUIRED>
<!ELEMENT fuseauHoraire (#PCDATA)>
<!ELEMENT statut (#PCDATA)>
<!ATTLIST statut derniereConnexion CDATA #REQUIRED>

<!-- Préférences -->
<!ELEMENT preferences (apparence, accessibilite, notifications, securite, stockage, connectivite, parametresIA)>
<!ELEMENT apparence (theme, police, animations)>
<!ELEMENT theme (#PCDATA)>
<!ELEMENT police EMPTY>
<!ATTLIST police taille CDATA #IMPLIED famille CDATA #IMPLIED>
<!ELEMENT animations EMPTY>
<!ATTLIST animations active (true|false) #REQUIRED>

<!ELEMENT accessibilite (syntheseVocale, hautContraste, navigationClavier)>
<!ELEMENT syntheseVocale EMPTY>
<!ATTLIST syntheseVocale active (true|false) #REQUIRED>
<!ELEMENT hautContraste EMPTY>
<!ATTLIST hautContraste active (true|false) #REQUIRED>
<!ELEMENT navigationClavier EMPTY>
<!ATTLIST navigationClavier active (true|false) #REQUIRED>

<!ELEMENT notifications (global, horaireSilence?, son?, vibration?, popup?)>
<!ELEMENT global EMPTY>
<!ATTLIST global active (true|false) #REQUIRED>
<!ELEMENT horaireSilence EMPTY>
<!ATTLIST horaireSilence debut CDATA #REQUIRED fin CDATA #REQUIRED>
<!ELEMENT son EMPTY>
<!ATTLIST son volume CDATA #IMPLIED>
<!ELEMENT vibration EMPTY>
<!ATTLIST vibration modele CDATA #IMPLIED>
<!ELEMENT popup EMPTY>
<!ATTLIST popup duree CDATA #IMPLIED active (true|false) #REQUIRED>

<!ELEMENT securite (deconnexionAuto?, codePIN?, biometrie?, chiffrementLocal?)>
<!ELEMENT deconnexionAuto EMPTY>
<!ATTLIST deconnexionAuto delai CDATA #REQUIRED>
<!ELEMENT codePIN EMPTY>
<!ATTLIST codePIN 
    longueur CDATA #REQUIRED
    essaisMax CDATA #IMPLIED>
<!ELEMENT biometrie EMPTY>
<!ATTLIST biometrie active (true|false) #REQUIRED>
<!ELEMENT chiffrementLocal EMPTY>
<!ATTLIST chiffrementLocal 
    algo CDATA #REQUIRED
    active (true|false) #REQUIRED>

<!ELEMENT stockage (limiteMo, nettoyageAuto?, compressionMedia?)>
<!ELEMENT limiteMo (#PCDATA)>
<!ELEMENT nettoyageAuto EMPTY>
<!ATTLIST nettoyageAuto plusVieuxQue CDATA #REQUIRED>
<!ELEMENT compressionMedia EMPTY>
<!ATTLIST compressionMedia methode CDATA #REQUIRED>

<!ELEMENT connectivite (modeHorsLigne?, reseauxPreferes, modeEconomieDonnees?)>
<!ELEMENT modeHorsLigne EMPTY>
<!ATTLIST modeHorsLigne 
    active (true|false) #REQUIRED>
<!ELEMENT reseauxPreferes (reseau+)>
<!ELEMENT reseau EMPTY>
<!ATTLIST reseau type CDATA #REQUIRED
    priorite CDATA #REQUIRED>
<!ELEMENT modeEconomieDonnees EMPTY>
<!ATTLIST modeEconomieDonnees active (true|false) #REQUIRED>

<!ELEMENT parametresIA (reponsesIntelligentes?, analyseSentiment?, traductionAuto?, reconnaissanceVocale?)>
<!ELEMENT reponsesIntelligentes EMPTY>
<!ATTLIST reponsesIntelligentes active (true|false) #REQUIRED>
<!ELEMENT analyseSentiment EMPTY>
<!ATTLIST analyseSentiment active (true|false) #REQUIRED>
<!ELEMENT traductionAuto EMPTY>
<!ATTLIST traductionAuto cible CDATA #REQUIRED active (true|false) #REQUIRED>
<!ELEMENT reconnaissanceVocale EMPTY>
<!ATTLIST reconnaissanceVocale accent CDATA #REQUIRED>

<!-- Journal d'activité -->
<!ELEMENT journalActivite (entree*)>
<!ELEMENT entree EMPTY>
<!ATTLIST entree horodatage CDATA #REQUIRED type CDATA #REQUIRED detail CDATA #IMPLIED message CDATA #IMPLIED>

<!-- Contacts -->
<!ELEMENT contacts (contact+)>
<!ELEMENT contact EMPTY>
<!ATTLIST contact id ID #REQUIRED utilisateur IDREF #REQUIRED avec IDREF #REQUIRED depuis CDATA #REQUIRED favori (true|false) #IMPLIED>

<!-- Groupes -->
<!ELEMENT groupes (groupe+)>
<!ELEMENT groupe (meta, parametres, membres)>
<!ATTLIST groupe id ID #REQUIRED>
<!ELEMENT meta (nom, photo?, type, creePar, description)>
<!ELEMENT creePar EMPTY>
<!ATTLIST creePar utilisateur IDREF #REQUIRED date CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT parametres (politiqueInvit?, retentionHistorique?, traductionAuto?, chiffrement?, tailleMaxMembres?, modeRapide?)>
<!ELEMENT politiqueInvit EMPTY>
<!ATTLIST politiqueInvit invitationsPar CDATA #REQUIRED>
<!ELEMENT retentionHistorique EMPTY>
<!ATTLIST retentionHistorique jours CDATA #REQUIRED>
<!ELEMENT chiffrement EMPTY>
<!ATTLIST chiffrement finAFin (true|false) #REQUIRED>
<!ELEMENT tailleMaxMembres (#PCDATA)>
<!ELEMENT modeRapide EMPTY>
<!ATTLIST modeRapide intervalle CDATA #REQUIRED>
<!ELEMENT membres (membre+)>
<!ELEMENT membre EMPTY>
<!ATTLIST membre utilisateur IDREF #REQUIRED role CDATA #REQUIRED rejoint CDATA #REQUIRED>

<!-- Messages -->
<!ELEMENT messages (message+)>
<!ELEMENT message (contenu, options?, securiteMessage?, statistiques?, ameliorementsIA?)>
<!ATTLIST message id ID #REQUIRED de IDREF #REQUIRED a IDREF #IMPLIED horodatage CDATA #REQUIRED statut CDATA #REQUIRED aGroupe IDREF #IMPLIED>
<!ELEMENT contenu (texte?, formatage?, fichier?, audio?, transcription*)>
<!ATTLIST contenu type (texte|fichier|audio|video) #REQUIRED>
<!ELEMENT texte (#PCDATA)>
<!ELEMENT formatage EMPTY>
<!ATTLIST formatage gras (true|false) #IMPLIED italique (true|false) #IMPLIED>
<!ELEMENT fichier EMPTY>
<!ATTLIST fichier nom CDATA #REQUIRED mime CDATA #REQUIRED tailleKo CDATA #REQUIRED>
<!ELEMENT audio EMPTY>
<!ATTLIST audio source CDATA #REQUIRED duree CDATA #REQUIRED>
<!ELEMENT video EMPTY>
<!ATTLIST video source CDATA #REQUIRED duree CDATA #REQUIRED>
<!ELEMENT transcription (#PCDATA)>
<!ATTLIST transcription lang CDATA #REQUIRED>

<!ELEMENT options (priorite?, ephemere?, accuseLecture?, reactionsPossible?, transfert?, analyseVirus?, ouvertureAutoInvite?)>
<!ELEMENT priorite EMPTY>
<!ATTLIST priorite niveau CDATA #REQUIRED>
<!ELEMENT ephemere EMPTY>
<!ATTLIST ephemere duree CDATA #REQUIRED>
<!ELEMENT accuseLecture EMPTY>
<!ATTLIST accuseLecture demande (true|false) #REQUIRED>
<!ELEMENT reactionsPossible EMPTY>
<!ATTLIST reactionsPossible types CDATA #REQUIRED>
<!ELEMENT transfert EMPTY>
<!ATTLIST transfert autorise (true|false) #REQUIRED>
<!ELEMENT analyseVirus EMPTY>
<!ATTLIST analyseVirus effectue (true|false) #REQUIRED resultat CDATA #REQUIRED>
<!ELEMENT ouvertureAutoInvite EMPTY>
<!ATTLIST ouvertureAutoInvite active (true|false) #REQUIRED>

<!ELEMENT securiteMessage (filigrane?, signature?)>
<!ELEMENT filigrane EMPTY>
<!ATTLIST filigrane actif (true|false) #REQUIRED>
<!ELEMENT signature (#PCDATA)>
<!ATTLIST signature algo CDATA #REQUIRED>

<!ELEMENT statistiques (telechargements?)>
<!ELEMENT telechargements (#PCDATA)>

<!ELEMENT ameliorementsIA (reductionBruit?, emotionDetectee?)>
<!ELEMENT reductionBruit EMPTY>
<!ATTLIST reductionBruit appliquee (true|false) #REQUIRED>
<!ELEMENT emotionDetectee (#PCDATA)>

<!-- Notifications (niveau racine) -->
<!ELEMENT notificationsRacine (notification+)>
<!ELEMENT notification (contenuNotification, action)>
<!ATTLIST notification id ID #REQUIRED pour IDREF #REQUIRED declencheur IDREF #REQUIRED type CDATA #REQUIRED date CDATA #REQUIRED lue (true|false) #REQUIRED>
<!ELEMENT contenuNotification (#PCDATA)>
<!ELEMENT action EMPTY>
<!ATTLIST action onClick CDATA #REQUIRED>

<!-- Plugins -->
<!ELEMENT mod:plugins (mod:plugin+)>
<!ELEMENT mod:plugin (mod:configuration?, mod:regles?)>
<!ATTLIST mod:plugin nom CDATA #REQUIRED active (true|false) #REQUIRED>
<!ELEMENT mod:configuration (mod:serveursICE?, mod:codecVideo?)>
<!ELEMENT mod:serveursICE (mod:serveur+)>
<!ELEMENT mod:serveur EMPTY>
<!ATTLIST mod:serveur url CDATA #REQUIRED utilisateur CDATA #IMPLIED motDePasse CDATA #IMPLIED>
<!ELEMENT mod:codecVideo (#PCDATA)>
<!ELEMENT mod:regles (mod:regle+)>
<!ELEMENT mod:regle (mod:quand, mod:reponse, mod:delai)>
<!ATTLIST mod:regle id ID #REQUIRED>
<!ELEMENT mod:quand (#PCDATA)>
<!ELEMENT mod:reponse (#PCDATA)>
<!ELEMENT mod:delai (#PCDATA)>

<!-- Bus d'événements -->
<!ELEMENT evt:busEvenements (evt:canal+)>
<!ELEMENT evt:canal EMPTY>
<!ATTLIST evt:canal nom CDATA #REQUIRED gestionnaire CDATA #REQUIRED>

<!-- CRDT -->
<!ELEMENT crdt:documents (crdt:document+)>
<!ELEMENT crdt:document (crdt:type, crdt:etat)>
<!ATTLIST crdt:document id ID #REQUIRED>
<!ELEMENT crdt:type (#PCDATA)>
<!ELEMENT crdt:etat (#PCDATA)>

<!-- Observabilité -->
<!ELEMENT observabilite (metriques?, traces?, journalisation?)>
<!ELEMENT metriques (metrique+)>
<!ELEMENT metrique EMPTY>
<!ATTLIST metrique nom CDATA #REQUIRED type (compteur|jauge) #REQUIRED>
<!ELEMENT traces (endpointTrace, echantillonnage)>
<!ELEMENT endpointTrace (#PCDATA)>
<!ELEMENT echantillonnage EMPTY>
<!ATTLIST echantillonnage taux CDATA #REQUIRED>
<!ELEMENT journalisation EMPTY>
<!ATTLIST journalisation niveau CDATA #REQUIRED format CDATA #REQUIRED>

<!-- Pipeline -->
<!ELEMENT pipeline (ci, cd)>
<!ELEMENT ci (etape+)>
<!ELEMENT etape EMPTY>
<!ATTLIST etape nom CDATA #REQUIRED commande CDATA #REQUIRED>
<!ELEMENT cd (deploiement)>
<!ELEMENT deploiement EMPTY>
<!ATTLIST deploiement environnement CDATA #REQUIRED strategie CDATA #REQUIRED>

<!-- Config système -->
<!ELEMENT configurationSysteme (infoAppli, performance, sauvegarde, conformite)>
<!ELEMENT infoAppli (nom, version, dateCompilation)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT dateCompilation (#PCDATA)>
<!ELEMENT performance (threadsMax, cache, niveauJournal)>
<!ELEMENT threadsMax (#PCDATA)>
<!ELEMENT cache EMPTY>
<!ATTLIST cache active (true|false) #REQUIRED dureeVie CDATA #REQUIRED>
<!ELEMENT niveauJournal (#PCDATA)>
<!ELEMENT sauvegarde (planning, conservation, emplacement, chiffrementSauvegarde)>
<!ELEMENT planning EMPTY>
<!ATTLIST planning quotidienne CDATA #REQUIRED incrementale (true|false) #REQUIRED>
<!ELEMENT conservation EMPTY>
<!ATTLIST conservation jours CDATA #REQUIRED>
<!ELEMENT emplacement (#PCDATA)>
<!ELEMENT chiffrementSauvegarde EMPTY>
<!ATTLIST chiffrementSauvegarde active (true|false) #REQUIRED>
<!ELEMENT conformite (rgpdCompliant, traceAudit)>
<!ELEMENT rgpdCompliant (#PCDATA)>
<!ELEMENT traceAudit EMPTY>
<!ATTLIST traceAudit active (true|false) #REQUIRED>

=== mohamethlo/Projet_XML_Technologie/applichat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appliChat SYSTEM "applichat.dtd">
<appliChat xmlns="http://exemple.com/chat"
           xmlns:cfg="http://exemple.com/chat/config"
           xmlns:mod="http://exemple.com/chat/modules"
           xmlns:evt="http://exemple.com/chat/evenements"
           xmlns:crdt="http://exemple.com/chat/crdt"
           version="3.0"
           genereLe="2025-07-11T16:00:00Z">

  <!-- 1. Environnements & Flags de fonctionnalités -->
  <cfg:environnements>
    <cfg:env nom="developpement">
      <cfg:endpointAPI>http://localhost:8000/api</cfg:endpointAPI>
      <cfg:flagsFonctionnalites>
        <cfg:flag nom="nouvelleUI" active="true"/>
        <cfg:flag nom="appelVocal" active="false"/>
      </cfg:flagsFonctionnalites>
    </cfg:env>
    <cfg:env nom="production">
      <cfg:endpointAPI>https://chat.exemple.com/api</cfg:endpointAPI>
      <cfg:flagsFonctionnalites>
        <cfg:flag nom="nouvelleUI" active="false"/>
        <cfg:flag nom="appelVocal" active="true"/>
      </cfg:flagsFonctionnalites>
    </cfg:env>
  </cfg:environnements>

  <!-- 2. Utilisateurs -->
  <utilisateurs>
    <utilisateur id="U100" cfg:env="production">
      <identifiants>
        <login>fatou.ndiaye</login>
        <motDePasse algoHash="bcrypt">$2a$12$EXEMPLEHASH…</motDePasse>
        <authentification2FA methode="sms" active="true"/>
      </identifiants>
      <profil>
        <nom>Fatou Ndiaye</nom>
        <photo>/images/U100.jpg</photo>
        <bio>Étudiante L3 Cybersécurité</bio>
        <languePreferee>fr</languePreferee>
        <languesDisponibles>
          <langue code="fr"/>
          <langue code="wo"/>
          <langue code="en"/>
        </languesDisponibles>
        <fuseauHoraire>Africa/Dakar</fuseauHoraire>
        <statut derniereConnexion="2025-07-11T15:45:00Z">active</statut>
      </profil>
      <preferences>
        <apparence>
          <theme>sombre</theme>
          <police taille="moyenne" famille="Arial"/>
          <animations active="false"/>
        </apparence>
        <accessibilite>
          <syntheseVocale active="true"/>
          <hautContraste active="true"/>
          <navigationClavier active="true"/>
        </accessibilite>
        <notifications>
          <global active="true"/>
          <horaireSilence debut="22:00" fin="06:00"/>
          <son volume="80"/>
          <vibration modele="court"/>
          <popup duree="5s" active="true"/>
        </notifications>
        <securite>
          <deconnexionAuto delai="15m"/>
          <codePIN longueur="6" essaisMax="3"/>
          <biometrie active="true"/>
          <chiffrementLocal algo="AES-256" active="true"/>
        </securite>
        <stockage>
          <limiteMo>1024</limiteMo>
          <nettoyageAuto plusVieuxQue="90j"/>
          <compressionMedia methode="gzip"/>
        </stockage>
        <connectivite>
          <modeHorsLigne active="true"/>
          <reseauxPreferes>
            <reseau type="WiFi" priorite="1"/>
            <reseau type="4G" priorite="2"/>
            <reseau type="2G" priorite="3"/>
          </reseauxPreferes>
          <modeEconomieDonnees active="true"/>
        </connectivite>
        <parametresIA>
          <reponsesIntelligentes active="true"/>
          <analyseSentiment active="true"/>
          <traductionAuto cible="wo" active="true"/>
          <reconnaissanceVocale accent="senegalais"/>
        </parametresIA>
      </preferences>
      <journalActivite>
        <entree horodatage="2025-07-10T18:00:00Z" type="connexion" detail="WiFi ESP"/>
        <entree horodatage="2025-07-10T20:15:00Z" type="messageEnvoye" message="M123"/>
      </journalActivite>
    </utilisateur>
    <!-- Ajout des utilisateurs U101 et U102 référencés -->
    <utilisateur id="U101">
      <identifiants>
        <login>user.101</login>
        <motDePasse algoHash="bcrypt">$2a$12$EXEMPLEHASH2…</motDePasse>
      </identifiants>
      <profil>
        <nom>Utilisateur 101</nom>
        <photo>/images/U101.jpg</photo>
        <languePreferee>fr</languePreferee>
        <languesDisponibles>
          <langue code="fr"/>
        </languesDisponibles>
        <fuseauHoraire>Africa/Dakar</fuseauHoraire>
        <statut derniereConnexion="2025-07-11T14:00:00Z">active</statut>
      </profil>
      <preferences>
        <apparence>
          <theme>clair</theme>
          <police taille="moyenne" famille="Arial"/>
          <animations active="true"/>
        </apparence>
        <accessibilite>
          <syntheseVocale active="false"/>
          <hautContraste active="false"/>
          <navigationClavier active="false"/>
        </accessibilite>
        <notifications>
          <global active="true"/>
        </notifications>
        <securite>
          <deconnexionAuto delai="30m"/>
        </securite>
        <stockage>
          <limiteMo>512</limiteMo>
        </stockage>
        <connectivite>
          <reseauxPreferes>
            <reseau type="WiFi" priorite="1"/>
          </reseauxPreferes>
        </connectivite>
        <parametresIA>
          <reponsesIntelligentes active="false"/>
        </parametresIA>
      </preferences>
    </utilisateur>
    <utilisateur id="U102">
      <identifiants>
        <login>user.102</login>
        <motDePasse algoHash="bcrypt">$2a$12$EXEMPLEHASH3…</motDePasse>
      </identifiants>
      <profil>
        <nom>Utilisateur 102</nom>
        <photo>/images/U102.jpg</photo>
        <languePreferee>fr</languePreferee>
        <languesDisponibles>
          <langue code="fr"/>
        </languesDisponibles>
        <fuseauHoraire>Africa/Dakar</fuseauHoraire>
        <statut derniereConnexion="2025-07-11T13:00:00Z">active</statut>
      </profil>
      <preferences>
        <apparence>
          <theme>clair</theme>
          <police taille="moyenne" famille="Arial"/>
          <animations active="true"/>
        </apparence>
        <accessibilite>
          <syntheseVocale active="false"/>
          <hautContraste active="false"/>
          <navigationClavier active="false"/>
        </accessibilite>
        <notifications>
          <global active="true"/>
        </notifications>
        <securite>
          <deconnexionAuto delai="30m"/>
        </securite>
        <stockage>
          <limiteMo>512</limiteMo>
        </stockage>
        <connectivite>
          <reseauxPreferes>
            <reseau type="WiFi" priorite="1"/>
          </reseauxPreferes>
        </connectivite>
        <parametresIA>
          <reponsesIntelligentes active="false"/>
        </parametresIA>
      </preferences>
    </utilisateur>
  </utilisateurs>

  <!-- 3. Contacts -->
  <contacts>
    <contact id="C001" utilisateur="U100" avec="U101" depuis="2025-06-15" favori="true"/>
    <contact id="C002" utilisateur="U100" avec="U102" depuis="2025-07-01"/>
  </contacts>

  <!-- 4. Groupes -->
  <groupes>
    <groupe id="G101">
      <meta>
        <nom>Projet IA Hackathon</nom>
        <photo>/groups/G101.png</photo>
        <type>prive</type>
        <creePar utilisateur="U100" date="2025-05-20"/>
        <description>Groupe de travail IA SENELEC 2025</description>
      </meta>
      <parametres>
        <politiqueInvit invitationsPar="adminSeul"/>
        <retentionHistorique jours="180"/>
        <traductionAuto cible="fr" active="false"/>
        <chiffrement finAFin="true"/>
        <tailleMaxMembres>50</tailleMaxMembres>
        <modeRapide intervalle="30s"/>
      </parametres>
      <membres>
        <membre utilisateur="U100" role="admin" rejoint="2025-05-20"/>
        <membre utilisateur="U101" role="membre" rejoint="2025-05-21"/>
      </membres>
    </groupe>
  </groupes>

  <!-- 5. Messages -->
  <messages>
    <message id="M501" de="U100" a="U101" horodatage="2025-07-11T12:00:00Z" statut="livré">
      <contenu type="texte">
        <texte>As‑tu vu le rapport final ?</texte>
        <formatage gras="true" italique="false"/>
      </contenu>
      <options>
        <priorite niveau="élevée"/>
        <ephemere duree="24h"/>
        <accuseLecture demande="true"/>
        <reactionsPossible types="toutes"/>
        <transfert autorise="false"/>
      </options>
      <securiteMessage>
        <filigrane actif="true"/>
        <signature algo="RSA-SHA256">BASE64SIG…</signature>
      </securiteMessage>
    </message>

    <message id="M502" de="U101" aGroupe="G101" horodatage="2025-07-11T12:05:00Z" statut="lu">
      <contenu type="fichier">
        <fichier nom="resultats.xlsx"
                 mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                 tailleKo="256"/>
      </contenu>
      <options>
        <analyseVirus effectue="true" resultat="propre"/>
        <ouvertureAutoInvite active="false"/>
      </options>
      <statistiques>
        <telechargements>3</telechargements>
      </statistiques>
    </message>

    <message id="M503" de="U102" a="U100" horodatage="2025-07-11T12:10:00Z" statut="envoyé">
      <contenu type="audio">
        <audio source="/media/U102/audio001.ogg" duree="12s"/>
        <transcription lang="fr">Je suis en route.</transcription>
      </contenu>
      <ameliorementsIA>
        <reductionBruit appliquee="true"/>
        <emotionDetectee>neutre</emotionDetectee>
      </ameliorementsIA>
    </message>

    <!-- Ajout du message M123 référencé -->
    <message id="M123" de="U100" a="U101" horodatage="2025-07-10T20:15:00Z" statut="lu">
      <contenu type="texte">
        <texte>Message de test</texte>
      </contenu>
    </message>
  </messages>

  <!-- 6. Notifications -->
  <notificationsRacine>
    <notification id="N1001" pour="U100" declencheur="M501" type="message" date="2025-07-11T12:00:10Z" lue="false">
      <contenuNotification>Fatou vous a envoyé un message.</contenuNotification>
      <action onClick="ouvrirDiscussion('U100','U101')"/>
    </notification>
  </notificationsRacine>

  <!-- 7. Plugins & Modules -->
  <mod:plugins>
